### ISSUE TITLE
Vacances scolaire et férié 

### ISSUE THREAD

**Issue by Hydci** [papo-o/home-assistant-config#3]
Bonjour @papo-o 

Je me permet de te contacter pour te soumettre une demande sur un groupe Facebook en parlant avec quelqu'un nous voulions passer par l'api domogeek pour les vacances on a vu ta méthode utilisé avec les académies mais avec certaine personne le sensor plante j'ai regarder pour adapter mais je comprend pas trop :( je souhaiterais donc savoir si tu pouvais nous sortir un petit truc avec l'api vu ton niveau de maîtrise cela ne devrais pas être trop difficile je pense 

Voici le lien de l'api http://domogeek.entropialux.com/static/doc/index.html
Voici par exemple pour ma zone la demande de vacances http://domogeek.entropialux.com/schoolholiday/B/now

Si par exemple dans l’entité ça pouvais mettre vacances oui ou non et pouvant être utilisé dans une automatisation et si le sensor pouvais s'actualiser par exemple a 2h00 ou 3h00 du matin :)
Si cela et faisable ça serait super 

Merci d'avance

**Comment by papo-o** [comment]
> avec certaine personne le sensor plante
Bonjour Hydci
utilisent ils la derniere version de ce script?
pour domogeek je n'utilise pas.  Je regarderai à l'occasion

**Comment by Hydci** [comment]
Bonjour @papo-o 

Pour la dernière version du script je sais pas je vais leur demander peut-être qu'il n'est pas a jour.
Merci de regarder un truc super simple ça serait génial juste une interrogation de l'api et un oui et non dans le sensor un truc qui te prendrais pas de temps a faire :) pour la gestions des volets lumière etc ça serait top

**Comment by papo-o** [comment]
cela te convient il ?
https://github.com/papo-o/home-assistant-config/blob/master/integrations/vacances_domogeek.yaml

**Comment by Hydci** [comment]
Bonsoir @papo-o ,
Effectivement cela et très bien c'est un super boulot que tu as sorti la :) 
On n'avais trouver ça mais ta solution et bien plus complète merci je pense opter pour la tienne du coup :)
```yaml
sensor:
  - platform: season
  - platform: rest
    name: vacances 
    json_attributes:
      - schoolholiday
    resource: http://domogeek.entropialux.com/schoolholiday/B/now/json
    value_template: '{{ value_json.schoolholiday }}'
    scan_interval: 120 
    headers: 
     User-Agent: Home Assistant
     Content-Type: application/json
```
